{
  "nbformat": 4,
  "nbformat_minor": 0,
  "metadata": {
    "colab": {
      "name": "ZeroDown Conevntion_Preprocessing.ipynb",
      "provenance": []
    },
    "kernelspec": {
      "name": "python3",
      "display_name": "Python 3"
    },
    "language_info": {
      "name": "python"
    }
  },
  "cells": [
    {
      "cell_type": "code",
      "execution_count": null,
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "6d1Q-zoYxwGD",
        "outputId": "87f7d18c-b5e2-476c-895f-d68b2a0032b6"
      },
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "Collecting geopandas\n",
            "  Downloading geopandas-0.10.2-py2.py3-none-any.whl (1.0 MB)\n",
            "\u001b[K     |████████████████████████████████| 1.0 MB 4.9 MB/s \n",
            "\u001b[?25hRequirement already satisfied: shapely>=1.6 in /usr/local/lib/python3.7/dist-packages (from geopandas) (1.8.1.post1)\n",
            "Collecting pyproj>=2.2.0\n",
            "  Downloading pyproj-3.2.1-cp37-cp37m-manylinux2010_x86_64.whl (6.3 MB)\n",
            "\u001b[K     |████████████████████████████████| 6.3 MB 51.5 MB/s \n",
            "\u001b[?25hCollecting fiona>=1.8\n",
            "  Downloading Fiona-1.8.21-cp37-cp37m-manylinux2014_x86_64.whl (16.7 MB)\n",
            "\u001b[K     |████████████████████████████████| 16.7 MB 41.2 MB/s \n",
            "\u001b[?25hRequirement already satisfied: pandas>=0.25.0 in /usr/local/lib/python3.7/dist-packages (from geopandas) (1.3.5)\n",
            "Requirement already satisfied: certifi in /usr/local/lib/python3.7/dist-packages (from fiona>=1.8->geopandas) (2021.10.8)\n",
            "Collecting click-plugins>=1.0\n",
            "  Downloading click_plugins-1.1.1-py2.py3-none-any.whl (7.5 kB)\n",
            "Requirement already satisfied: six>=1.7 in /usr/local/lib/python3.7/dist-packages (from fiona>=1.8->geopandas) (1.15.0)\n",
            "Requirement already satisfied: attrs>=17 in /usr/local/lib/python3.7/dist-packages (from fiona>=1.8->geopandas) (21.4.0)\n",
            "Requirement already satisfied: click>=4.0 in /usr/local/lib/python3.7/dist-packages (from fiona>=1.8->geopandas) (7.1.2)\n",
            "Collecting cligj>=0.5\n",
            "  Downloading cligj-0.7.2-py3-none-any.whl (7.1 kB)\n",
            "Collecting munch\n",
            "  Downloading munch-2.5.0-py2.py3-none-any.whl (10 kB)\n",
            "Requirement already satisfied: setuptools in /usr/local/lib/python3.7/dist-packages (from fiona>=1.8->geopandas) (57.4.0)\n",
            "Requirement already satisfied: pytz>=2017.3 in /usr/local/lib/python3.7/dist-packages (from pandas>=0.25.0->geopandas) (2018.9)\n",
            "Requirement already satisfied: python-dateutil>=2.7.3 in /usr/local/lib/python3.7/dist-packages (from pandas>=0.25.0->geopandas) (2.8.2)\n",
            "Requirement already satisfied: numpy>=1.17.3 in /usr/local/lib/python3.7/dist-packages (from pandas>=0.25.0->geopandas) (1.21.5)\n",
            "Installing collected packages: munch, cligj, click-plugins, pyproj, fiona, geopandas\n",
            "Successfully installed click-plugins-1.1.1 cligj-0.7.2 fiona-1.8.21 geopandas-0.10.2 munch-2.5.0 pyproj-3.2.1\n",
            "Requirement already satisfied: plotly in /usr/local/lib/python3.7/dist-packages (5.5.0)\n",
            "Requirement already satisfied: tenacity>=6.2.0 in /usr/local/lib/python3.7/dist-packages (from plotly) (8.0.1)\n",
            "Requirement already satisfied: six in /usr/local/lib/python3.7/dist-packages (from plotly) (1.15.0)\n"
          ]
        }
      ],
      "source": [
        "!pip install geopandas\n",
        "!pip install plotly "
      ]
    },
    {
      "cell_type": "code",
      "source": [
        "import pymongo\n",
        "from pymongo import MongoClient\n",
        "import pprint\n",
        "import datetime"
      ],
      "metadata": {
        "id": "6vzAE12IIAA_"
      },
      "execution_count": null,
      "outputs": []
    },
    {
      "cell_type": "code",
      "source": [
        "import pandas as pd"
      ],
      "metadata": {
        "id": "USEtkof3vbBs"
      },
      "execution_count": null,
      "outputs": []
    },
    {
      "cell_type": "code",
      "source": [
        "import geopandas  as gpd\n",
        "import matplotlib.pyplot as plt"
      ],
      "metadata": {
        "id": "V8euxvR9AyOI"
      },
      "execution_count": null,
      "outputs": []
    },
    {
      "cell_type": "code",
      "source": [
        "data=pd.read_csv('/content/drive/MyDrive/zero/Convention_Centers_Fairgrounds.csv')"
      ],
      "metadata": {
        "id": "3H_jGIdZBOO4"
      },
      "execution_count": null,
      "outputs": []
    },
    {
      "cell_type": "code",
      "source": [
        "data.head()"
      ],
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/",
          "height": 490
        },
        "id": "X31EltmcBlvC",
        "outputId": "6c8c8b1d-7ae2-4d99-a820-c00dddf7489d"
      },
      "execution_count": null,
      "outputs": [
        {
          "output_type": "execute_result",
          "data": {
            "text/plain": [
              "              X             Y  OBJECTID  CONV_ID  \\\n",
              "0 -9.603671e+06  3.816326e+06         1       62   \n",
              "1 -1.276142e+07  3.850495e+06         2      200   \n",
              "2 -1.024107e+07  4.058537e+06         3      125   \n",
              "3 -1.027150e+07  4.129777e+06         4      106   \n",
              "4 -1.027195e+07  4.129855e+06         5      113   \n",
              "\n",
              "                           NAME                       ADDRESS         CITY  \\\n",
              "0          THE GARRETT COLISEUM            1555 FEDERAL DRIVE   MONTGOMERY   \n",
              "1             YUMA CIVIC CENTER  1440 WEST DESERT HILLS DRIVE         YUMA   \n",
              "2  PINE BLUFF CONVENTION CENTER     1 CONVENTION CENTER PLAZA   PINE BLUFF   \n",
              "3  STATEHOUSE CONVENTION CENTER           101 S SPRING STREET  LITTLE ROCK   \n",
              "4               ROBINSON CENTER       426 WEST MARKHAM STREET  LITTLE ROCK   \n",
              "\n",
              "  STATE    ZIP           ZIP4  ...             FORMERNM       YEARCHNG  \\\n",
              "0    AL  36107  NOT AVAILABLE  ...        NOT AVAILABLE  NOT AVAILABLE   \n",
              "1    AZ  85365  NOT AVAILABLE  ...        NOT AVAILABLE  NOT AVAILABLE   \n",
              "2    AR  71601  NOT AVAILABLE  ...        NOT AVAILABLE  NOT AVAILABLE   \n",
              "3    AR  72201  NOT AVAILABLE  ...        NOT AVAILABLE  NOT AVAILABLE   \n",
              "4    AR  72203  NOT AVAILABLE  ...  ROBINSON AUDITORIUM  NOT AVAILABLE   \n",
              "\n",
              "  FIXED_STS BALLROOM  EXHIBIT LOBBY  MAIN_FLOOR  OUTDOOR  PRE_FUNCT MEET_ROOMS  \n",
              "0         Y        N        N     N           Y        N          N          N  \n",
              "1         N        Y        Y     N           N        Y          N          Y  \n",
              "2         Y        Y        N     N           Y        N          N          Y  \n",
              "3         N        Y        Y     N           N        N          Y          Y  \n",
              "4         N        N        Y     Y           N        N          N          Y  \n",
              "\n",
              "[5 rows x 36 columns]"
            ],
            "text/html": [
              "\n",
              "  <div id=\"df-180540eb-cf3c-443a-8f9f-161b7c8b1382\">\n",
              "    <div class=\"colab-df-container\">\n",
              "      <div>\n",
              "<style scoped>\n",
              "    .dataframe tbody tr th:only-of-type {\n",
              "        vertical-align: middle;\n",
              "    }\n",
              "\n",
              "    .dataframe tbody tr th {\n",
              "        vertical-align: top;\n",
              "    }\n",
              "\n",
              "    .dataframe thead th {\n",
              "        text-align: right;\n",
              "    }\n",
              "</style>\n",
              "<table border=\"1\" class=\"dataframe\">\n",
              "  <thead>\n",
              "    <tr style=\"text-align: right;\">\n",
              "      <th></th>\n",
              "      <th>X</th>\n",
              "      <th>Y</th>\n",
              "      <th>OBJECTID</th>\n",
              "      <th>CONV_ID</th>\n",
              "      <th>NAME</th>\n",
              "      <th>ADDRESS</th>\n",
              "      <th>CITY</th>\n",
              "      <th>STATE</th>\n",
              "      <th>ZIP</th>\n",
              "      <th>ZIP4</th>\n",
              "      <th>...</th>\n",
              "      <th>FORMERNM</th>\n",
              "      <th>YEARCHNG</th>\n",
              "      <th>FIXED_STS</th>\n",
              "      <th>BALLROOM</th>\n",
              "      <th>EXHIBIT</th>\n",
              "      <th>LOBBY</th>\n",
              "      <th>MAIN_FLOOR</th>\n",
              "      <th>OUTDOOR</th>\n",
              "      <th>PRE_FUNCT</th>\n",
              "      <th>MEET_ROOMS</th>\n",
              "    </tr>\n",
              "  </thead>\n",
              "  <tbody>\n",
              "    <tr>\n",
              "      <th>0</th>\n",
              "      <td>-9.603671e+06</td>\n",
              "      <td>3.816326e+06</td>\n",
              "      <td>1</td>\n",
              "      <td>62</td>\n",
              "      <td>THE GARRETT COLISEUM</td>\n",
              "      <td>1555 FEDERAL DRIVE</td>\n",
              "      <td>MONTGOMERY</td>\n",
              "      <td>AL</td>\n",
              "      <td>36107</td>\n",
              "      <td>NOT AVAILABLE</td>\n",
              "      <td>...</td>\n",
              "      <td>NOT AVAILABLE</td>\n",
              "      <td>NOT AVAILABLE</td>\n",
              "      <td>Y</td>\n",
              "      <td>N</td>\n",
              "      <td>N</td>\n",
              "      <td>N</td>\n",
              "      <td>Y</td>\n",
              "      <td>N</td>\n",
              "      <td>N</td>\n",
              "      <td>N</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>1</th>\n",
              "      <td>-1.276142e+07</td>\n",
              "      <td>3.850495e+06</td>\n",
              "      <td>2</td>\n",
              "      <td>200</td>\n",
              "      <td>YUMA CIVIC CENTER</td>\n",
              "      <td>1440 WEST DESERT HILLS DRIVE</td>\n",
              "      <td>YUMA</td>\n",
              "      <td>AZ</td>\n",
              "      <td>85365</td>\n",
              "      <td>NOT AVAILABLE</td>\n",
              "      <td>...</td>\n",
              "      <td>NOT AVAILABLE</td>\n",
              "      <td>NOT AVAILABLE</td>\n",
              "      <td>N</td>\n",
              "      <td>Y</td>\n",
              "      <td>Y</td>\n",
              "      <td>N</td>\n",
              "      <td>N</td>\n",
              "      <td>Y</td>\n",
              "      <td>N</td>\n",
              "      <td>Y</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>2</th>\n",
              "      <td>-1.024107e+07</td>\n",
              "      <td>4.058537e+06</td>\n",
              "      <td>3</td>\n",
              "      <td>125</td>\n",
              "      <td>PINE BLUFF CONVENTION CENTER</td>\n",
              "      <td>1 CONVENTION CENTER PLAZA</td>\n",
              "      <td>PINE BLUFF</td>\n",
              "      <td>AR</td>\n",
              "      <td>71601</td>\n",
              "      <td>NOT AVAILABLE</td>\n",
              "      <td>...</td>\n",
              "      <td>NOT AVAILABLE</td>\n",
              "      <td>NOT AVAILABLE</td>\n",
              "      <td>Y</td>\n",
              "      <td>Y</td>\n",
              "      <td>N</td>\n",
              "      <td>N</td>\n",
              "      <td>Y</td>\n",
              "      <td>N</td>\n",
              "      <td>N</td>\n",
              "      <td>Y</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>3</th>\n",
              "      <td>-1.027150e+07</td>\n",
              "      <td>4.129777e+06</td>\n",
              "      <td>4</td>\n",
              "      <td>106</td>\n",
              "      <td>STATEHOUSE CONVENTION CENTER</td>\n",
              "      <td>101 S SPRING STREET</td>\n",
              "      <td>LITTLE ROCK</td>\n",
              "      <td>AR</td>\n",
              "      <td>72201</td>\n",
              "      <td>NOT AVAILABLE</td>\n",
              "      <td>...</td>\n",
              "      <td>NOT AVAILABLE</td>\n",
              "      <td>NOT AVAILABLE</td>\n",
              "      <td>N</td>\n",
              "      <td>Y</td>\n",
              "      <td>Y</td>\n",
              "      <td>N</td>\n",
              "      <td>N</td>\n",
              "      <td>N</td>\n",
              "      <td>Y</td>\n",
              "      <td>Y</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>4</th>\n",
              "      <td>-1.027195e+07</td>\n",
              "      <td>4.129855e+06</td>\n",
              "      <td>5</td>\n",
              "      <td>113</td>\n",
              "      <td>ROBINSON CENTER</td>\n",
              "      <td>426 WEST MARKHAM STREET</td>\n",
              "      <td>LITTLE ROCK</td>\n",
              "      <td>AR</td>\n",
              "      <td>72203</td>\n",
              "      <td>NOT AVAILABLE</td>\n",
              "      <td>...</td>\n",
              "      <td>ROBINSON AUDITORIUM</td>\n",
              "      <td>NOT AVAILABLE</td>\n",
              "      <td>N</td>\n",
              "      <td>N</td>\n",
              "      <td>Y</td>\n",
              "      <td>Y</td>\n",
              "      <td>N</td>\n",
              "      <td>N</td>\n",
              "      <td>N</td>\n",
              "      <td>Y</td>\n",
              "    </tr>\n",
              "  </tbody>\n",
              "</table>\n",
              "<p>5 rows × 36 columns</p>\n",
              "</div>\n",
              "      <button class=\"colab-df-convert\" onclick=\"convertToInteractive('df-180540eb-cf3c-443a-8f9f-161b7c8b1382')\"\n",
              "              title=\"Convert this dataframe to an interactive table.\"\n",
              "              style=\"display:none;\">\n",
              "        \n",
              "  <svg xmlns=\"http://www.w3.org/2000/svg\" height=\"24px\"viewBox=\"0 0 24 24\"\n",
              "       width=\"24px\">\n",
              "    <path d=\"M0 0h24v24H0V0z\" fill=\"none\"/>\n",
              "    <path d=\"M18.56 5.44l.94 2.06.94-2.06 2.06-.94-2.06-.94-.94-2.06-.94 2.06-2.06.94zm-11 1L8.5 8.5l.94-2.06 2.06-.94-2.06-.94L8.5 2.5l-.94 2.06-2.06.94zm10 10l.94 2.06.94-2.06 2.06-.94-2.06-.94-.94-2.06-.94 2.06-2.06.94z\"/><path d=\"M17.41 7.96l-1.37-1.37c-.4-.4-.92-.59-1.43-.59-.52 0-1.04.2-1.43.59L10.3 9.45l-7.72 7.72c-.78.78-.78 2.05 0 2.83L4 21.41c.39.39.9.59 1.41.59.51 0 1.02-.2 1.41-.59l7.78-7.78 2.81-2.81c.8-.78.8-2.07 0-2.86zM5.41 20L4 18.59l7.72-7.72 1.47 1.35L5.41 20z\"/>\n",
              "  </svg>\n",
              "      </button>\n",
              "      \n",
              "  <style>\n",
              "    .colab-df-container {\n",
              "      display:flex;\n",
              "      flex-wrap:wrap;\n",
              "      gap: 12px;\n",
              "    }\n",
              "\n",
              "    .colab-df-convert {\n",
              "      background-color: #E8F0FE;\n",
              "      border: none;\n",
              "      border-radius: 50%;\n",
              "      cursor: pointer;\n",
              "      display: none;\n",
              "      fill: #1967D2;\n",
              "      height: 32px;\n",
              "      padding: 0 0 0 0;\n",
              "      width: 32px;\n",
              "    }\n",
              "\n",
              "    .colab-df-convert:hover {\n",
              "      background-color: #E2EBFA;\n",
              "      box-shadow: 0px 1px 2px rgba(60, 64, 67, 0.3), 0px 1px 3px 1px rgba(60, 64, 67, 0.15);\n",
              "      fill: #174EA6;\n",
              "    }\n",
              "\n",
              "    [theme=dark] .colab-df-convert {\n",
              "      background-color: #3B4455;\n",
              "      fill: #D2E3FC;\n",
              "    }\n",
              "\n",
              "    [theme=dark] .colab-df-convert:hover {\n",
              "      background-color: #434B5C;\n",
              "      box-shadow: 0px 1px 3px 1px rgba(0, 0, 0, 0.15);\n",
              "      filter: drop-shadow(0px 1px 2px rgba(0, 0, 0, 0.3));\n",
              "      fill: #FFFFFF;\n",
              "    }\n",
              "  </style>\n",
              "\n",
              "      <script>\n",
              "        const buttonEl =\n",
              "          document.querySelector('#df-180540eb-cf3c-443a-8f9f-161b7c8b1382 button.colab-df-convert');\n",
              "        buttonEl.style.display =\n",
              "          google.colab.kernel.accessAllowed ? 'block' : 'none';\n",
              "\n",
              "        async function convertToInteractive(key) {\n",
              "          const element = document.querySelector('#df-180540eb-cf3c-443a-8f9f-161b7c8b1382');\n",
              "          const dataTable =\n",
              "            await google.colab.kernel.invokeFunction('convertToInteractive',\n",
              "                                                     [key], {});\n",
              "          if (!dataTable) return;\n",
              "\n",
              "          const docLinkHtml = 'Like what you see? Visit the ' +\n",
              "            '<a target=\"_blank\" href=https://colab.research.google.com/notebooks/data_table.ipynb>data table notebook</a>'\n",
              "            + ' to learn more about interactive tables.';\n",
              "          element.innerHTML = '';\n",
              "          dataTable['output_type'] = 'display_data';\n",
              "          await google.colab.output.renderOutput(dataTable, element);\n",
              "          const docLink = document.createElement('div');\n",
              "          docLink.innerHTML = docLinkHtml;\n",
              "          element.appendChild(docLink);\n",
              "        }\n",
              "      </script>\n",
              "    </div>\n",
              "  </div>\n",
              "  "
            ]
          },
          "metadata": {},
          "execution_count": 17
        }
      ]
    },
    {
      "cell_type": "code",
      "source": [
        "data['COMPLEXNM'].unique()"
      ],
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "4vZ67_DWDLcM",
        "outputId": "28ec8504-5855-4268-cff1-a824309b3e94"
      },
      "execution_count": null,
      "outputs": [
        {
          "output_type": "execute_result",
          "data": {
            "text/plain": [
              "array(['THE ALABAMA AGRICULTURAL CENTER', 'NOT APPLICABLE',\n",
              "       'FRESNO CONVENTION AND ENTERTAINMENT CENTER',\n",
              "       'FAIRPLEX POMONA CALIFORNIA', 'PASADENA CONVENTION CENTER',\n",
              "       'SAFE CREDIT UNION CONVENTION AND PERFORMING ARTS DISTRICT',\n",
              "       'CAL EXPO', 'FLORIDA STATE FAIRGROUNDS',\n",
              "       'ORANGE COUNTY CONVENTION CENTER', 'GEORGIA WORLD CONGRESS CENTER',\n",
              "       'ATLANTA EXPO CENTERS', 'GWINNETT CENTER',\n",
              "       'LAMAR DIXON EXPO CENTER', 'ONCENTER COMPLEX', 'EXPO SQUARE',\n",
              "       'LANE EVENTS CENTER', 'LINN COUNTY EXPO CENTER',\n",
              "       'TRAVIS COUNTY EXPOSITION CENTER',\n",
              "       'THE NATIONAL CONFERENCE CENTER', 'THREE RIVERS CAMPUS',\n",
              "       'CLARK COUNTY EVENT CENTER AT THE FAIRGROUNDS',\n",
              "       'BIRMINGHAM-JEFFERSON CONVENTION COMPLEX', 'VON BRAUN CENTER',\n",
              "       'MESA CONVENTION CENTER', 'PHOENIX CONVENTION CENTER',\n",
              "       'ARIZONA EXPOSITION AND STATE FAIRGROUNDS',\n",
              "       'OC FAIR AND EVENT CENTER', 'SAN MATEO EVENT CENTER', 'COW PALACE',\n",
              "       'CAJUNDOME AND CONVENTION CENTER', 'THE RIVERCENTER',\n",
              "       'NATIONAL WESTERN COMPLEX', 'OSCEOLA HERITAGE PARK',\n",
              "       'MACON CENTERPLEX COLISUEM AND CONVENTION CENTER',\n",
              "       'AUGUSTA ENTERTAINMENT COMPLEX', 'MCCORMICK PLACE',\n",
              "       'CHARLOTTE CONVENTION CENTER',\n",
              "       'DULUTH ENTERTAINMENT CONVENTION CENTER',\n",
              "       'KANSAS CITY CONVENTION CENTER', 'GOLDEN SPIKE EVENT CENTER',\n",
              "       'DESCHUTES COUNTY FAIRGROUNDS EXPO CENTER',\n",
              "       'CHARLESTON AREA CONVENTION CENTER CAMPUS',\n",
              "       'JUNEAU ARTS & HUMANITIES COUNCIL', 'DEL MAR FAIRGROUNDS',\n",
              "       'RENO-SPARKS LIVESTOCK EVENTS CENTER', 'CROWN COMPLEX',\n",
              "       'AGRICENTER INTERNATIONAL', 'FREEMAN COLISEUM AND EXPO HALL',\n",
              "       'CHARLESTON CIVIC CENTER', 'CLAY COUNTY FAIR AND EVENTS CENTER',\n",
              "       'NEAL S. BLAISDELL CENTER', 'LONE STAR CONVENTION AND EXPO CENTER',\n",
              "       'MGM GRAND', 'AUGUSTA EXPO EVENT CENTER', 'YORK EXPO CENTER',\n",
              "       'LEXINGTON CENTER', 'CAPITAL COMPLEX',\n",
              "       'BANCORPSOUTH ARENA AND CONFERENCE CENTER',\n",
              "       'THE GEORGE MOSCONE CENTER', 'CENTURYLINK FIELD', 'SEATTLE CENTER',\n",
              "       'SUNNYVIEW EXPOSITION CENTER', 'WILL ROGERS MEMORIAL CENTER',\n",
              "       'IOWA EVENTS CENTER', 'THE EASTERN STATES EXPOSITION',\n",
              "       'MAUDE COBB CONVENTION AND ACTIVITY COMPLEX', 'BARRE CIVIC CENTER',\n",
              "       'ELKO CONFERENCE AND CONVENTION CENTER', 'SAINT PAUL RIVERCENTRE',\n",
              "       'ALBUQUERQUE CONVENTION CENTER', 'AMERICAN BANK CENTER',\n",
              "       'AMARILLO CIVIC CENTER COMPLEX', 'TRI-STATE EXPO',\n",
              "       'BELL COUNTY EXPOSITION CENTER', 'BERGLUND CENTER',\n",
              "       'OXNARD PERFORMING ARTS AND CONVENTION CENTER',\n",
              "       'ALLIANT ENERGY CENTER', 'OHIO EXPO CENTER AND STATE FAIRGROUNDS',\n",
              "       'RACINE CIVIC CENTRE', 'WAUKESHA EXPO CENTER',\n",
              "       'CENTRAL NATIONAL BANK CENTER', 'WYE RIVER CONFERENCE CENTER',\n",
              "       \"AMERICA'S CENTER CONVENTION COMPLEX\", 'METRAPARK',\n",
              "       'INDIANA STATE FAIRGROUNDS',\n",
              "       'INDIANA CONVENTION CENTER AND LUCAS OIL STADIUM',\n",
              "       'KANSAS EXPOCENTRE', 'ISLAND GROVE REGIONAL PARK',\n",
              "       'PASADENA CONVENTION CENTER AND MUNICIPAL FAIRGROUNDS', 'NRG PARK',\n",
              "       'WISCONSIN STATE FAIR PARK', 'DENNY SANFORD PREMIER CENTER',\n",
              "       'TRI-RIVERS FAIRGROUNDS', 'DIVOTS CONFERENCE CENTER',\n",
              "       'WICHITA FALLS MULTI-PURPOSE EVENT CENTER',\n",
              "       'CHI HEALTH CENTER OMAHA', 'GETTYSBURG ALLSTAR EXPO COMPLEX',\n",
              "       'EXPO IDAHO', 'WASHINGTON COUNTY CONVENTION CENTER COMPLEX',\n",
              "       'INTERNATIONAL AGRI-CENTER',\n",
              "       'MARIPOSA FAIRGROUNDS & EXPOSITION CENTER',\n",
              "       'MIAMI-DADE COUNTY FAIR & EXPOSITION',\n",
              "       'THE JACKSONVILLE FAIRGROUNDS', 'THE SOUTH FLORIDA EXPO CENTER',\n",
              "       'EXPOSITION GARDENS', 'NEW YORK STATE FAIRGROUNDS',\n",
              "       'HEART OF OKLAHOMA EXPOSITION CENTER',\n",
              "       'CHILHOWEE PARK & EXPOSITION CENTER', 'CHELAN COUNTY EXPO CENTER',\n",
              "       'GRAYS HARBOR FAIR & EVENT CENTER',\n",
              "       'SPOKANE COUNTY FAIR AND EXPO CENTER',\n",
              "       'MANITOWOC COUNTY EXPO CENTER', 'AIRLIE',\n",
              "       'NATIONAL 4-H CONFERENCE CENTER',\n",
              "       'TOMMY DOUGLAS CONFERENCE CENTER',\n",
              "       'UNIVERSITY OF LOUISVILLE EVENT AND CONFERENCE SERVICE CENTER - SHELBYHURST CAMPUS',\n",
              "       'LAKE JUNALUSKA CONFERENCE & RETREAT CENTER',\n",
              "       'SCARRITT BENNETT CENTER',\n",
              "       'BELL HARBOR INTERNATIONAL CONFERENCE CENTER',\n",
              "       'VENTURA COUNTY FAIRGROUNDS AND EVENT CENTER',\n",
              "       'PASO ROBLES EVENT CENTER', 'VOLUSIA COUNTY FAIRGROUNDS',\n",
              "       'FORD IDAHO CENTER COMPLEX', 'BURTON MEMORIAL COLISEUM COMPLEX',\n",
              "       'FOX CITIES EXHIBITION CENTER', 'RESCH CENTER COMPLEX',\n",
              "       'EMBASSY SUITES NORTHWEST ARKANSAS - HOTEL, SPA AND CONVENTION CENTER',\n",
              "       'THE BROADMOOR', 'NORRIS PENROSE EVENT CENTER',\n",
              "       'ARAPAHOE COUNTY FAIRGROUNDS AND PARK',\n",
              "       'COWETA COUNTY CONFERENCE CENTER AND FAIRGROUNDS',\n",
              "       'IOWA STATE CENTER', 'DICKINSON COUNTY FAIRGROUNDS',\n",
              "       'DUPAGE COUNTY FAIRGROUNDS', 'SHIPSHEWANA TRADING PLACE',\n",
              "       'CAPITOL PLAZA HOTEL AND CONVENTION CENTER - TOPEKA',\n",
              "       \"THE SHOW PLACE ARENA AND PRINCE GEORGE'S EQUESTRIAN CENTER\",\n",
              "       'PEARL RIVER RESORT', 'WINNEMUCCA EVENTS COMPLEX',\n",
              "       'STATE FAIR PARK', 'WATERFRONT HOTEL AND CONVENTION CENTER',\n",
              "       'GREATER GULF STATE FAIRGROUNDS',\n",
              "       'TANANA VALLEY STATE FAIRGROUNDS',\n",
              "       'KENAI PENINSULA STATE FAIRGROUNDS', 'ALASKA STATE FAIRGROUNDS',\n",
              "       'ARKANSAS STATE FAIRGROUNDS', 'COLORADO STATE FAIRGROUNDS',\n",
              "       'DELAWARE STATE FAIRGROUNDS', 'EASTERN IDAHO STATE FAIRGROUNDS',\n",
              "       'ILLINOIS STATE FAIRGROUNDS', 'IOWA STATE FAIRGROUNDS',\n",
              "       'KANSAS STATE FAIRGROUNDS', 'LOUISIANA STATE FAIRGROUNDS',\n",
              "       'SKOWHEGAN STATE FAIRGROUNDS', 'MARYLAND STATE FAIRGROUNDS',\n",
              "       'MINNESOTA STATE FAIRGROUNDS', 'MISSOURI STATE FAIRGROUNDS',\n",
              "       'MISSISSIPPI COLISEUM AND FAIRGROUNDS', 'MONTANA EXPOPARK',\n",
              "       'SUSSEX COUNTY FAIRGROUNDS (NJ STATE FAIR)', 'EXPO NEW MEXICO',\n",
              "       'NORTH DAKOTA STATE FAIRGROUNDS',\n",
              "       'NORTH CAROLINA STATE FAIRGROUNDS',\n",
              "       'OREGON STATE FAIR AND EXPOSITION CENTER',\n",
              "       'SOUTH CAROLINA STATE FAIRGROUNDS',\n",
              "       'SOUTH DAKOTA STATE FAIRGROUNDS', 'THE FAIRGROUNDS NASHVILLE',\n",
              "       'FAIR PARK (STATE FAIR OF TEXAS)', 'NORTH TEXAS STATE FAIRGROUNDS',\n",
              "       'UTAH STATE FAIRPARK (UTAH STATE FAIR)',\n",
              "       'PUYALLUP FAIR AND EVENTS CENTER', 'EVERGREEN STATE FAIRGROUNDS',\n",
              "       'STATE FAIR PARK (CENTRAL WASH ST. FAIR)',\n",
              "       'STATE FAIRGROUNDS OF WEST VIRGINIA', 'WYOMING STATE FAIRGROUNDS',\n",
              "       'GEORGIA NATIONAL FAIRGROUNDS & AGRICENTER',\n",
              "       'JIM MILLER PARK (NORTH GEORGIA STATE FAIR)',\n",
              "       'DUQUOIN STATE FAIRGROUNDS', 'UPPER PENINSULA STATE FAIRGROUNDS',\n",
              "       'FONNER PARK (NEBRASKA STATE FAIR)',\n",
              "       'SOUTHERN NEW MEXICO STATE FAIRGROUNDS',\n",
              "       'WNC AGRICULTURAL CENTER (NC STATE FAIR)',\n",
              "       'FORD PARK (SOUTH TEXAS STATE FAIR)',\n",
              "       'EAST TEXAS STATE FAIRGROUNDS',\n",
              "       'MEADOW EVENT PARK (STATE FAIR OF VIRGINIA)',\n",
              "       'NORTHWEST WASHINGTON FAIR & EVENT CENTER',\n",
              "       'CENTRAL WISCONSIN STATE FAIRGROUNDS',\n",
              "       'NORTHERN WISCONSIN STATE FAIRGROUNDS',\n",
              "       'NAVAJO NATION FAIRGROUNDS', 'KOOTENAI COUNTY FAIRGROUNDS',\n",
              "       \"MAINE'S FRYEBURG FAIRGROUNDS\",\n",
              "       'WINSTON-SALEM FAIRGROUNDS (DIXIE CLASSIC FAIR)',\n",
              "       'ALLENTOWN FAIRGROUNDS', 'BLOOMSBURG FAIRGROUNDS',\n",
              "       'INDUSTRY HILLS EXPO CENTER',\n",
              "       'EXPO NEW MEXICO (NEW MEXICO STATE FAIR)',\n",
              "       'OKANOGAN COUNTY FAIRGROUNDS', 'KIWANIS COVINGTON COUNTY FAIR',\n",
              "       'BALDWIN COUNTY COLISEUM AND FAIRGROUNDS',\n",
              "       'JACKSON COUNTY FAIRGROUNDS', 'PENSACOLA INTERSTATE FAIR',\n",
              "       'PIMA COUNTY FAIRGROUNDS', 'YUMA COUNTY FAIRGROUNDS',\n",
              "       'BAXTER COUNTY FAIRGROUNDS',\n",
              "       'KAY RODGERS PARK (ARKANSAS-OKLAHOMA STATE FAIR)',\n",
              "       'BENTON COUNTY FAIRGROUNDS AND EXPO CENTER', 'INDIO FAIRGROUNDS',\n",
              "       'NATIONAL ORANGE SHOW EVENT CENTER', 'AV FAIR AND EVENT CENTER',\n",
              "       'DESERT EMPIRE FAIRGROUNDS AND EVENTS CENTER',\n",
              "       'TULARE COUNTY FAIRGROUNDS', 'FRESNO FAIRGROUNDS',\n",
              "       'MADERA DISTRICT FAIRGROUNDS', 'TRI COUNTY FAIR AND EVENT CENTER',\n",
              "       'MERCED COUNTY FAIRGROUNDS', 'STANISLAUS COUNTY FAIRGROUNDS',\n",
              "       'SANTA CLARA COUNTY FAIRGROUNDS', 'ALAMEDA COUNTY FAIRGROUNDS',\n",
              "       'CONTRA COSTA EVENT PARK', 'MOTHER LODE FAIRGROUNDS',\n",
              "       'CALAVERAS COUNTY FAIRGROUNDS',\n",
              "       'LODI GRAPE FESTIVAL AND EVENT CENTER',\n",
              "       'MARIN COUNTY FAIRGROUNDS AND EXPOSITION',\n",
              "       'SOLANO COUNTY FAIRGROUNDS',\n",
              "       'AMADOR COUNTY FAIRGROUNDS AND EVENT CENTER',\n",
              "       'EL DORADO COUNTY FAIR AND EVENT CENTER',\n",
              "       'GOLD COUNTRY FAIRGROUNDS AND EVENT CENTER',\n",
              "       'SONOMA COUNTY EVENT CENTER AT THE FAIRGROUNDS',\n",
              "       'CLOVERDALE CITRUS FAIRGROUNDS', 'MENDOCINO COUNTY FAIRGROUNDS',\n",
              "       'REDWOOD EMPIRE FAIR AND EVENT CENTER',\n",
              "       'SILVER DOLLAR FAIRGROUNDS', 'GLENN COUNTY FAIRGROUNDS',\n",
              "       'LASSEN COUNTY FAIRGROUNDS',\n",
              "       'SHASTA DISTRICT FAIR AND EVENT CENTER',\n",
              "       'INTER MOUNTAIN FAIR AND EVENT CENTER',\n",
              "       'HUMBOLDT COUNTY FAIRGROUNDS', 'REDWOOD ACRES',\n",
              "       'TRINITY COUNTY FAIRGROUNDS AND EVENT CENTER',\n",
              "       'SISKIYOU GOLDEN FAIRGROUNDS', 'MESA COUNTY FAIRGROUNDS',\n",
              "       'LA PLATA COUNTY FAIRGROUNDS AND EVENTS CENTER',\n",
              "       'EAGLE COUNTY FAIRGROUNDS', 'BOULDER COUNTY FAIRGROUNDS',\n",
              "       'RIVERDALE REGIONAL PARK AND FAIRGROUNDS',\n",
              "       'EL PASO COUNTY FAIR AND EVENTS CENTER', 'JEFFCO FAIRGROUNDS',\n",
              "       'ELKHART COUNTY 4-H FAIRGROUNDS',\n",
              "       'SAINT JOSEPH COUNTY 4-H FAIRGROUNDS', 'MONROE COUNTY FAIRGROUNDS',\n",
              "       'MONTGOMERY COUNTY AGRICULTURAL FAIRGROUNDS',\n",
              "       'THE GREAT FREDERICK FAIRGROUNDS', 'HOWARD COUNTY FAIRGROUNDS',\n",
              "       'CARROLL COUNTY AGRICULTURE CENTER AND SHIPLEY ARENA',\n",
              "       'ALLEGANY COUNTY FAIRGROUNDS', 'DURHAM FAIRGROUNDS',\n",
              "       'TOLLAND COUNTY AGRICULTURAL CENTER', 'NORTH FLORIDA FAIRGROUNDS',\n",
              "       'PAUL E REINHOLD AGRICULTURAL FAIRGROUNDS',\n",
              "       'SOUTHWEST FLORIDA AND LEE COUNTY FAIRGROUNDS',\n",
              "       'PASCO COUNTY FAIRGROUNDS',\n",
              "       'CENTRAL FLORIDA FAIR AND EXPOSITION PARK',\n",
              "       'BRADFORD COUNTY FAIRGROUNDS',\n",
              "       'PUTNAM COUNTY FAIRGROUNDS AND EXPO CENTER',\n",
              "       'SAINT LUCIE COUNTY FAIRGROUNDS EQUESTRIAN AND EVENT CENTER',\n",
              "       'THE CHARLOTTE COUNTY FAIRGROUNDS', 'SARASOTA FAIRGROUNDS',\n",
              "       'EXCHANGE CLUB FAIRGROUNDS', 'CUMMING FAIRGROUNDS',\n",
              "       'GWINNETT COUNTY FAIRGROUNDS', 'BONNER COUNTY FAIRGROUNDS',\n",
              "       'CANYON COUNTY FAIRGROUNDS AND CALDWELL EVENTS CENTER',\n",
              "       'TETON COUNTY FAIRGROUNDS', 'TWIN FALLS COUNTY FAIRGROUNDS',\n",
              "       'LATAH COUNTY FAIRGROUNDS AND EVENTS CENTER',\n",
              "       'LAKE COUNTY FAIRGROUNDS AND EVENT CENTER',\n",
              "       'STEPHENSON COUNTY FAIRGROUNDS', 'KANE COUNTY FAIRGROUNDS',\n",
              "       'BOONE COUNTY FAIRGROUNDS (ILLINOIS)',\n",
              "       'BOONE COUNTY 4-H FAIRGROUNDS', 'BOONE COUNTY FAIRGROUNDS (IOWA)',\n",
              "       'MACON COUNTY FAIRGROUNDS', 'MORGAN COUNTY FAIRGROUNDS',\n",
              "       'WINNEBAGO COUNTY FAIRGROUNDS', 'DEL NORTE COUNTY FAIRGROUNDS',\n",
              "       'COLUSA COUNTY FAIRGROUNDS', 'IMPERIAL VALLEY FAIRGROUNDS',\n",
              "       'KINGS COUNTY FAIRGROUNDS', 'LAKE COUNTY FAIRGROUNDS',\n",
              "       'MONTEREY FAIRGROUNDS AND EVENT CENTER',\n",
              "       'NAPA VALLEY EXPO AND FAIRGROUNDS', 'NEVADA COUNTY FAIRGROUNDS',\n",
              "       'PLUMAS COUNTY FAIRGROUNDS', 'BOLADO PARK EVENT CENTER',\n",
              "       'SBC FAIRGROUNDS', 'SANTA MARIA FAIRPARK',\n",
              "       'SANTA CRUZ COUNTY FAIRGROUNDS AND EVENT CENTER',\n",
              "       'YUBA-SUTTER FAIRGROUNDS AND EVENT CENTER',\n",
              "       'TEHAMA DISTRICT FAIRGROUNDS', 'YOLO COUNTY FAIRGROUNDS',\n",
              "       'ALLEN COUNTY FAIRGROUNDS', 'BARTHOLOMEW COUNTY 4-H FAIRGROUNDS',\n",
              "       'CASS COUNTY 4-H FAIRGROUNDS', 'CLINTON COUNTY FAIRGROUNDS',\n",
              "       'DECATUR COUNTY FAIRGROUNDS AND EXHIBITION CENTER',\n",
              "       'DELAWARE COUNTY FAIRGROUNDS', 'GIBSON COUNTY FAIRGROUNDS',\n",
              "       'HAMILTON COUNTY FAIRGROUNDS', 'HARRISON COUNTY FAIRGROUNDS',\n",
              "       'HENDRICKS COUNTY 4-H FAIRGROUNDS AND CONFERENCE COMPLEX',\n",
              "       'JASPER COUNTY FAIRGROUNDS', 'JAY COUNTY FAIR',\n",
              "       'JOHNSON COUNTY FAIRGROUNDS', 'LAPORTE COUNTY FAIRGROUNDS',\n",
              "       'MARION COUNTY FAIRGROUNDS', 'PORTER COUNTY EXPO CENTER',\n",
              "       'PUTNAM COUNTY FAIRGROUNDS', 'RUSH COUNTY FAIRGROUNDS',\n",
              "       'VANDERBURGH 4-H CENTER', 'WAYNE COUNTY FAIRGROUNDS',\n",
              "       'WHITLEY COUNTY FAIRGROUNDS', 'NORTH IOWA EVENTS CENTER',\n",
              "       'CHEROKEE COUNTY FAIRGROUNDS', 'DALLAS COUNTY FAIRGROUNDS',\n",
              "       'DUBUQUE COUNTY FAIRGROUNDS', 'GREENE COUNTY FAIRGROUNDS',\n",
              "       'JONES COUNTY FAIRGROUNDS', 'KEOKUK COUNTY FAIRGROUNDS',\n",
              "       'SOUTHERN IOWA FAIRGROUNDS', 'MISSISSIPPI VALLEY FAIRGROUNDS',\n",
              "       'WEBSTER COUNTY FAIRGROUNDS', 'PINAL FAIRGROUNDS AND EVENT CENTER',\n",
              "       'COLUMBIA COUNTY FAIRGROUNDS', 'FULTON COUNTY FAIRGROUNDS',\n",
              "       'DOUGLAS COUNTY FAIRGROUNDS AND EVENTS CENTER',\n",
              "       'ESTES PARK EVENTS COMPLEX', 'THE RANCH EVENTS COMPLEX',\n",
              "       'MONTROSE COUNTY EVENT CENTER AND FAIRGROUNDS',\n",
              "       'MODOC DISTRICT FAIRGROUNDS', 'SALINAS VALLEY FAIRGROUNDS',\n",
              "       'PLACER COUNTY FAIRGROUNDS', 'COLORADO RIVER FAIRGROUNDS',\n",
              "       'SAN JOAQUIN COUNTY FAIRGROUNDS', 'EARL WARREN SHOWGROUNDS',\n",
              "       'SONOMA-MARIN FAIRGROUNDS', 'HARDEE COUNTY FAIRGROUNDS',\n",
              "       'INDIAN RIVER COUNTY FAIRGROUNDS AND EXPO CENTER',\n",
              "       'FLORIDA STRAWBERRY FESTIVAL', 'WINFIELD FAIRGROUNDS',\n",
              "       'DOUGLAS COUNTY FAIRGROUNDS',\n",
              "       'GRANT COUNTY CIVIC CENTER AND FAIRGROUNDS',\n",
              "       'LYON COUNTY FAIRGROUNDS', 'WEST-CAL ARENA AND EVENTS CENTER',\n",
              "       'NORTHERN MAINE FAIRGROUNDS', 'SPENCER FAIRGROUNDS',\n",
              "       'THREE COUNTY FAIRGROUNDS', 'TOPSFIELD FAIRGROUNDS',\n",
              "       'BERRIEN COUNTY FAIRGROUNDS', 'CALHOUN COUNTY FAIRGROUNDS',\n",
              "       'KEELEY PARK', 'MIDLAND COUNTY FAIRGROUNDS', 'IONIA FAIRGROUNDS',\n",
              "       'LENAWEE COUNTY FAIRGROUNDS', 'SPRINGFIELD OAKS COUNTY PARK',\n",
              "       'WASHTENAW FAIRGROUNDS', 'ALLEGAN COUNTY FAIRGROUNDS',\n",
              "       'SAINT JOSEPH COUNTY FAIRGROUNDS', 'CARVER COUNTY FAIRGROUNDS',\n",
              "       'CROW WING COUNTY FAIRGROUNDS', 'DAKOTA COUNTY FAIRGROUNDS',\n",
              "       'FARIBAULT COUNTY FAIRGROUNDS', 'HUBBARD COUNTY FAIRGROUNDS',\n",
              "       'MARTIN COUNTY FAIRGROUNDS', 'MCLEOD COUNTY FAIRGROUNDS',\n",
              "       'MOWER COUNTY FAIRGROUNDS', 'SCOTT COUNTY FAIRGROUNDS',\n",
              "       'STEELE COUNTY FAIRGROUNDS', 'WADENA COUNTY FAIRGROUNDS',\n",
              "       'JAMES LYNN CARTLIDGE FORREST COUNTY MULTI-PURPOSE CENTER',\n",
              "       'NEMO FAIRGROUNDS', 'MONTGOMERY COUNTY FAIRGROUNDS',\n",
              "       'OZARK EMPIRE FAIRGROUNDS', 'GALLATIN COUNTY FAIRGROUNDS',\n",
              "       'FALLON COUNTY FAIRGROUNDS', 'LEWIS AND CLARK COUNTY FAIRGROUNDS',\n",
              "       'FLATHEAD COUNTY FAIRGROUNDS', 'RICHLAND COUNTY FAIRGROUNDS',\n",
              "       'MISSOULA COUNTY FAIRGROUNDS', 'BUFFALO COUNTY FAIRGROUNDS',\n",
              "       'SEWARD COUNTY FAIRGROUNDS', 'KEITH COUNTY FAIRGROUNDS',\n",
              "       'DAWSON COUNTY FAIRGROUNDS', 'ADAMS COUNTY FAIRGROUNDS',\n",
              "       'CASS COUNTY FAIRGROUNDS', 'WASHINGTON COUNTY FAIRGROUNDS',\n",
              "       'MADISON COUNTY FAIRGROUNDS', 'RED WILLOW COUNTY FAIRGROUNDS',\n",
              "       'SCOTTS BLUFF COUNTY FAIRGROUNDS', 'KIMMEL AG EXPO CENTER',\n",
              "       'MCGEE PARK', 'HEMLOCK FAIRGROUNDS', 'ERIE COUNTY FAIRGROUNDS',\n",
              "       'FONDA FAIRGROUNDS', 'HAYWOOD COUNTY FAIRGROUNDS',\n",
              "       'RED RIVER VALLEY FAIRGROUNDS', 'CENTRAL STATES FAIRGROUNDS',\n",
              "       'UPPER MISSOURI VALLEY FAIRGROUNDS', 'SIOUX EMPIRE FAIRGROUNDS',\n",
              "       'TURNER COUNTY FAIRGROUNDS', 'TRUMBULL COUNTY FAIRGROUNDS',\n",
              "       'FRANKLIN COUNTY FAIRGROUNDS', 'CRAWFORD COUNTY FAIRGROUNDS',\n",
              "       'WARREN COUNTY FAIRGROUNDS', 'CLARK COUNTY FAIRGROUNDS',\n",
              "       'THE CHAMPIONS CENTER EXPO', 'UNION COUNTY FAIRGROUNDS',\n",
              "       'PREBLE COUNTY FAIRGROUNDS', 'MEDINA COUNTY FAIRGROUNDS',\n",
              "       'CHAMPAIGN COUNTY FAIRGROUNDS', 'HARTFORD FAIRGROUNDS',\n",
              "       'HOLMES COUNTY FAIRGROUNDS', 'CUYAHOGA COUNTY FAIRGROUNDS',\n",
              "       'ASHTABULA COUNTY FAIRGROUNDS', 'HENRY COUNTY FAIRGROUNDS',\n",
              "       'MIAMI COUNTY FAIRGROUNDS', 'HURON COUNTY FAIRGROUNDS',\n",
              "       'PORTAGE COUNTY RANDOLPH FAIRGROUNDS',\n",
              "       'HANCOCK COUNTY FAIRGROUNDS', 'CANFIELD FAIRGROUNDS',\n",
              "       'HIGHLAND COUNTY FAIRGROUNDS', 'BELMONT COUNTY PARK FAIRGROUNDS',\n",
              "       'COMANCHE COUNTY FAIRGROUNDS', 'STEPHENS COUNTY FAIRGROUNDS',\n",
              "       'WOODWARD COUNTY EVENT CENTER AND FAIRGROUNDS',\n",
              "       'BLACKWELL FAIRGROUNDS AND EVENT CENTER',\n",
              "       'GRADY COUNTY FAIRGROUNDS AND EVENT CENTER',\n",
              "       'CLEVELAND COUNTY FAIRGROUNDS', 'BENTON COUNTY FAIRGROUNDS',\n",
              "       'CLACKAMAS COUNTY FAIRGROUNDS AND EVENT CENTER',\n",
              "       'GRANT COUNTY FAIRGROUNDS', 'JACKSON COUNTY EXPO',\n",
              "       'JEFFERSON COUNTY FAIRGROUNDS', 'JOSEPHINE COUNTY FAIRGROUNDS',\n",
              "       'KLAMATH COUNTY FAIRGROUNDS AND EVENT CENTER',\n",
              "       'POLK COUNTY FAIRGROUNDS AND EVENT CENTER',\n",
              "       'EASTERN OREGON TRADE AND EVENT CENTER', 'TROY FAIRGROUNDS',\n",
              "       'WEST END FAIRGROUNDS', 'KUTZTOWN FAIRGROUNDS',\n",
              "       'EXCHANGE PARK FAIRGROUNDS',\n",
              "       'EASTERN CAROLINA AGRICULTURAL FAIRGROUNDS',\n",
              "       'DYER COUNTY FAIRGROUNDS', 'TRI-STATE EXHIBITION CENTER',\n",
              "       'MATAGORDA COUNTY FAIRGROUNDS',\n",
              "       'AV \"BULL\" SALLAS PARK (EAST MONTGOMERY COUNTY FAIR)',\n",
              "       'EXTRACO EVENTS CENTER', 'KENDALL COUNTY FAIRGROUNDS',\n",
              "       'SAN PATRICIO COUNTY FAIRGROUNDS AND EVENT CENTER',\n",
              "       'MIDLAND COUNTY HORSESHOE', 'ECTOR COUNTY COLISEUM FAIRGROUNDS',\n",
              "       'RICHARD M BORCHARD REGIONAL FAIRGROUNDS',\n",
              "       'UVALDE COUNTY FAIRPLEX', 'DAVIS COUNTY FAIRGROUNDS',\n",
              "       'BOX ELDER COUNTY FAIRGROUNDS', 'SPANISH FORK FAIRGROUNDS',\n",
              "       'ROCKINGHAM COUNTY FAIRGROUNDS',\n",
              "       'SOUTHWEST WASHINGTON FAIRGROUNDS',\n",
              "       'ENUMCLAW EXPO AND EVENT CENTER', 'THURSTON COUNTY FAIRGROUNDS',\n",
              "       'SKAGIT COUNTY FAIRGROUNDS', 'CLALLAM COUNTY FAIRGROUNDS',\n",
              "       'KITSAP COUNTY FAIRGROUNDS EVENTS CENTER',\n",
              "       'WALLA WALLA COUNTY FAIRGROUNDS',\n",
              "       'WEST VIRGINIA INTERSTATE FAIRGROUND',\n",
              "       'CEDAR LAKES CONFERENCE CENTER', 'LANGLADE COUNTY FAIRGROUNDS',\n",
              "       'OZAUKEE COUNTY FAIRGROUNDS', 'SAUK COUNTY FAIRGROUNDS',\n",
              "       'SHEBOYGAN COUNTY FAIRGROUNDS',\n",
              "       'WASHINGTON COUNTY FAIR PARK AND CONFERENCE CENTER',\n",
              "       'WAUPACA COUNTY FAIRGROUNDS', 'CAM-PLEX MULTI-EVENT FACILITIES',\n",
              "       'CENTRAL WYOMING FAIRGROUNDS', 'FREMONT COUNTY FAIRGROUNDS',\n",
              "       'LARAMIE COUNTY FAIRGROUNDS', 'SUBLETTE COUNTY FAIRGROUNDS',\n",
              "       'SWEETWATER EVENTS COMPLEX', 'WESTON COUNTY FAIRGROUNDS',\n",
              "       'MONTGOMERY COUNTY FAIRGROUNDS AND EVENT CENTER'], dtype=object)"
            ]
          },
          "metadata": {},
          "execution_count": 26
        }
      ]
    },
    {
      "cell_type": "code",
      "source": [
        "data.columns"
      ],
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "Ha7pa2XzCPiU",
        "outputId": "6fdac9b7-0213-4aa9-9900-c52d911953d0"
      },
      "execution_count": null,
      "outputs": [
        {
          "output_type": "execute_result",
          "data": {
            "text/plain": [
              "Index(['X', 'Y', 'OBJECTID', 'CONV_ID', 'NAME', 'ADDRESS', 'CITY', 'STATE',\n",
              "       'ZIP', 'ZIP4', 'TELEPHONE', 'TYPE', 'STATUS', 'COUNTY', 'COUNTYFIPS',\n",
              "       'COUNTRY', 'LATITUDE', 'LONGITUDE', 'NAICS_CODE', 'NAICS_DESC',\n",
              "       'SOURCE', 'SOURCEDATE', 'VAL_METHOD', 'VAL_DATE', 'WEBSITE',\n",
              "       'COMPLEXNM', 'FORMERNM', 'YEARCHNG', 'FIXED_STS', 'BALLROOM', 'EXHIBIT',\n",
              "       'LOBBY', 'MAIN_FLOOR', 'OUTDOOR', 'PRE_FUNCT', 'MEET_ROOMS'],\n",
              "      dtype='object')"
            ]
          },
          "metadata": {},
          "execution_count": 19
        }
      ]
    },
    {
      "cell_type": "code",
      "source": [
        "data.drop(columns = ['ADDRESS','ZIP4','ZIP','VAL_METHOD'],inplace =True)"
      ],
      "metadata": {
        "id": "knfcarFnCV2m"
      },
      "execution_count": null,
      "outputs": []
    },
    {
      "cell_type": "code",
      "source": [
        "#DataCleaning\n",
        "#1.checking for null values in the first column\n",
        "data=data.dropna(axis=0)\n",
        "r,c=data.shape\n",
        "print(r,c)\n",
        "data.isnull()"
      ],
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/",
          "height": 506
        },
        "id": "Ry7CtcjcEMUo",
        "outputId": "a727b99a-b249-4035-8743-7ce172829156"
      },
      "execution_count": null,
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "5019 32\n"
          ]
        },
        {
          "output_type": "execute_result",
          "data": {
            "text/plain": [
              "          X      Y  OBJECTID  CONV_ID   NAME   CITY  STATE  TELEPHONE   TYPE  \\\n",
              "0     False  False     False    False  False  False  False      False  False   \n",
              "1     False  False     False    False  False  False  False      False  False   \n",
              "2     False  False     False    False  False  False  False      False  False   \n",
              "3     False  False     False    False  False  False  False      False  False   \n",
              "4     False  False     False    False  False  False  False      False  False   \n",
              "...     ...    ...       ...      ...    ...    ...    ...        ...    ...   \n",
              "5014  False  False     False    False  False  False  False      False  False   \n",
              "5015  False  False     False    False  False  False  False      False  False   \n",
              "5016  False  False     False    False  False  False  False      False  False   \n",
              "5017  False  False     False    False  False  False  False      False  False   \n",
              "5018  False  False     False    False  False  False  False      False  False   \n",
              "\n",
              "      STATUS  ...  FORMERNM  YEARCHNG  FIXED_STS  BALLROOM  EXHIBIT  LOBBY  \\\n",
              "0      False  ...     False     False      False     False    False  False   \n",
              "1      False  ...     False     False      False     False    False  False   \n",
              "2      False  ...     False     False      False     False    False  False   \n",
              "3      False  ...     False     False      False     False    False  False   \n",
              "4      False  ...     False     False      False     False    False  False   \n",
              "...      ...  ...       ...       ...        ...       ...      ...    ...   \n",
              "5014   False  ...     False     False      False     False    False  False   \n",
              "5015   False  ...     False     False      False     False    False  False   \n",
              "5016   False  ...     False     False      False     False    False  False   \n",
              "5017   False  ...     False     False      False     False    False  False   \n",
              "5018   False  ...     False     False      False     False    False  False   \n",
              "\n",
              "      MAIN_FLOOR  OUTDOOR  PRE_FUNCT  MEET_ROOMS  \n",
              "0          False    False      False       False  \n",
              "1          False    False      False       False  \n",
              "2          False    False      False       False  \n",
              "3          False    False      False       False  \n",
              "4          False    False      False       False  \n",
              "...          ...      ...        ...         ...  \n",
              "5014       False    False      False       False  \n",
              "5015       False    False      False       False  \n",
              "5016       False    False      False       False  \n",
              "5017       False    False      False       False  \n",
              "5018       False    False      False       False  \n",
              "\n",
              "[5019 rows x 32 columns]"
            ],
            "text/html": [
              "\n",
              "  <div id=\"df-06668314-3c60-4c9f-9f08-871b4123f88b\">\n",
              "    <div class=\"colab-df-container\">\n",
              "      <div>\n",
              "<style scoped>\n",
              "    .dataframe tbody tr th:only-of-type {\n",
              "        vertical-align: middle;\n",
              "    }\n",
              "\n",
              "    .dataframe tbody tr th {\n",
              "        vertical-align: top;\n",
              "    }\n",
              "\n",
              "    .dataframe thead th {\n",
              "        text-align: right;\n",
              "    }\n",
              "</style>\n",
              "<table border=\"1\" class=\"dataframe\">\n",
              "  <thead>\n",
              "    <tr style=\"text-align: right;\">\n",
              "      <th></th>\n",
              "      <th>X</th>\n",
              "      <th>Y</th>\n",
              "      <th>OBJECTID</th>\n",
              "      <th>CONV_ID</th>\n",
              "      <th>NAME</th>\n",
              "      <th>CITY</th>\n",
              "      <th>STATE</th>\n",
              "      <th>TELEPHONE</th>\n",
              "      <th>TYPE</th>\n",
              "      <th>STATUS</th>\n",
              "      <th>...</th>\n",
              "      <th>FORMERNM</th>\n",
              "      <th>YEARCHNG</th>\n",
              "      <th>FIXED_STS</th>\n",
              "      <th>BALLROOM</th>\n",
              "      <th>EXHIBIT</th>\n",
              "      <th>LOBBY</th>\n",
              "      <th>MAIN_FLOOR</th>\n",
              "      <th>OUTDOOR</th>\n",
              "      <th>PRE_FUNCT</th>\n",
              "      <th>MEET_ROOMS</th>\n",
              "    </tr>\n",
              "  </thead>\n",
              "  <tbody>\n",
              "    <tr>\n",
              "      <th>0</th>\n",
              "      <td>False</td>\n",
              "      <td>False</td>\n",
              "      <td>False</td>\n",
              "      <td>False</td>\n",
              "      <td>False</td>\n",
              "      <td>False</td>\n",
              "      <td>False</td>\n",
              "      <td>False</td>\n",
              "      <td>False</td>\n",
              "      <td>False</td>\n",
              "      <td>...</td>\n",
              "      <td>False</td>\n",
              "      <td>False</td>\n",
              "      <td>False</td>\n",
              "      <td>False</td>\n",
              "      <td>False</td>\n",
              "      <td>False</td>\n",
              "      <td>False</td>\n",
              "      <td>False</td>\n",
              "      <td>False</td>\n",
              "      <td>False</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>1</th>\n",
              "      <td>False</td>\n",
              "      <td>False</td>\n",
              "      <td>False</td>\n",
              "      <td>False</td>\n",
              "      <td>False</td>\n",
              "      <td>False</td>\n",
              "      <td>False</td>\n",
              "      <td>False</td>\n",
              "      <td>False</td>\n",
              "      <td>False</td>\n",
              "      <td>...</td>\n",
              "      <td>False</td>\n",
              "      <td>False</td>\n",
              "      <td>False</td>\n",
              "      <td>False</td>\n",
              "      <td>False</td>\n",
              "      <td>False</td>\n",
              "      <td>False</td>\n",
              "      <td>False</td>\n",
              "      <td>False</td>\n",
              "      <td>False</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>2</th>\n",
              "      <td>False</td>\n",
              "      <td>False</td>\n",
              "      <td>False</td>\n",
              "      <td>False</td>\n",
              "      <td>False</td>\n",
              "      <td>False</td>\n",
              "      <td>False</td>\n",
              "      <td>False</td>\n",
              "      <td>False</td>\n",
              "      <td>False</td>\n",
              "      <td>...</td>\n",
              "      <td>False</td>\n",
              "      <td>False</td>\n",
              "      <td>False</td>\n",
              "      <td>False</td>\n",
              "      <td>False</td>\n",
              "      <td>False</td>\n",
              "      <td>False</td>\n",
              "      <td>False</td>\n",
              "      <td>False</td>\n",
              "      <td>False</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>3</th>\n",
              "      <td>False</td>\n",
              "      <td>False</td>\n",
              "      <td>False</td>\n",
              "      <td>False</td>\n",
              "      <td>False</td>\n",
              "      <td>False</td>\n",
              "      <td>False</td>\n",
              "      <td>False</td>\n",
              "      <td>False</td>\n",
              "      <td>False</td>\n",
              "      <td>...</td>\n",
              "      <td>False</td>\n",
              "      <td>False</td>\n",
              "      <td>False</td>\n",
              "      <td>False</td>\n",
              "      <td>False</td>\n",
              "      <td>False</td>\n",
              "      <td>False</td>\n",
              "      <td>False</td>\n",
              "      <td>False</td>\n",
              "      <td>False</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>4</th>\n",
              "      <td>False</td>\n",
              "      <td>False</td>\n",
              "      <td>False</td>\n",
              "      <td>False</td>\n",
              "      <td>False</td>\n",
              "      <td>False</td>\n",
              "      <td>False</td>\n",
              "      <td>False</td>\n",
              "      <td>False</td>\n",
              "      <td>False</td>\n",
              "      <td>...</td>\n",
              "      <td>False</td>\n",
              "      <td>False</td>\n",
              "      <td>False</td>\n",
              "      <td>False</td>\n",
              "      <td>False</td>\n",
              "      <td>False</td>\n",
              "      <td>False</td>\n",
              "      <td>False</td>\n",
              "      <td>False</td>\n",
              "      <td>False</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>...</th>\n",
              "      <td>...</td>\n",
              "      <td>...</td>\n",
              "      <td>...</td>\n",
              "      <td>...</td>\n",
              "      <td>...</td>\n",
              "      <td>...</td>\n",
              "      <td>...</td>\n",
              "      <td>...</td>\n",
              "      <td>...</td>\n",
              "      <td>...</td>\n",
              "      <td>...</td>\n",
              "      <td>...</td>\n",
              "      <td>...</td>\n",
              "      <td>...</td>\n",
              "      <td>...</td>\n",
              "      <td>...</td>\n",
              "      <td>...</td>\n",
              "      <td>...</td>\n",
              "      <td>...</td>\n",
              "      <td>...</td>\n",
              "      <td>...</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>5014</th>\n",
              "      <td>False</td>\n",
              "      <td>False</td>\n",
              "      <td>False</td>\n",
              "      <td>False</td>\n",
              "      <td>False</td>\n",
              "      <td>False</td>\n",
              "      <td>False</td>\n",
              "      <td>False</td>\n",
              "      <td>False</td>\n",
              "      <td>False</td>\n",
              "      <td>...</td>\n",
              "      <td>False</td>\n",
              "      <td>False</td>\n",
              "      <td>False</td>\n",
              "      <td>False</td>\n",
              "      <td>False</td>\n",
              "      <td>False</td>\n",
              "      <td>False</td>\n",
              "      <td>False</td>\n",
              "      <td>False</td>\n",
              "      <td>False</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>5015</th>\n",
              "      <td>False</td>\n",
              "      <td>False</td>\n",
              "      <td>False</td>\n",
              "      <td>False</td>\n",
              "      <td>False</td>\n",
              "      <td>False</td>\n",
              "      <td>False</td>\n",
              "      <td>False</td>\n",
              "      <td>False</td>\n",
              "      <td>False</td>\n",
              "      <td>...</td>\n",
              "      <td>False</td>\n",
              "      <td>False</td>\n",
              "      <td>False</td>\n",
              "      <td>False</td>\n",
              "      <td>False</td>\n",
              "      <td>False</td>\n",
              "      <td>False</td>\n",
              "      <td>False</td>\n",
              "      <td>False</td>\n",
              "      <td>False</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>5016</th>\n",
              "      <td>False</td>\n",
              "      <td>False</td>\n",
              "      <td>False</td>\n",
              "      <td>False</td>\n",
              "      <td>False</td>\n",
              "      <td>False</td>\n",
              "      <td>False</td>\n",
              "      <td>False</td>\n",
              "      <td>False</td>\n",
              "      <td>False</td>\n",
              "      <td>...</td>\n",
              "      <td>False</td>\n",
              "      <td>False</td>\n",
              "      <td>False</td>\n",
              "      <td>False</td>\n",
              "      <td>False</td>\n",
              "      <td>False</td>\n",
              "      <td>False</td>\n",
              "      <td>False</td>\n",
              "      <td>False</td>\n",
              "      <td>False</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>5017</th>\n",
              "      <td>False</td>\n",
              "      <td>False</td>\n",
              "      <td>False</td>\n",
              "      <td>False</td>\n",
              "      <td>False</td>\n",
              "      <td>False</td>\n",
              "      <td>False</td>\n",
              "      <td>False</td>\n",
              "      <td>False</td>\n",
              "      <td>False</td>\n",
              "      <td>...</td>\n",
              "      <td>False</td>\n",
              "      <td>False</td>\n",
              "      <td>False</td>\n",
              "      <td>False</td>\n",
              "      <td>False</td>\n",
              "      <td>False</td>\n",
              "      <td>False</td>\n",
              "      <td>False</td>\n",
              "      <td>False</td>\n",
              "      <td>False</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>5018</th>\n",
              "      <td>False</td>\n",
              "      <td>False</td>\n",
              "      <td>False</td>\n",
              "      <td>False</td>\n",
              "      <td>False</td>\n",
              "      <td>False</td>\n",
              "      <td>False</td>\n",
              "      <td>False</td>\n",
              "      <td>False</td>\n",
              "      <td>False</td>\n",
              "      <td>...</td>\n",
              "      <td>False</td>\n",
              "      <td>False</td>\n",
              "      <td>False</td>\n",
              "      <td>False</td>\n",
              "      <td>False</td>\n",
              "      <td>False</td>\n",
              "      <td>False</td>\n",
              "      <td>False</td>\n",
              "      <td>False</td>\n",
              "      <td>False</td>\n",
              "    </tr>\n",
              "  </tbody>\n",
              "</table>\n",
              "<p>5019 rows × 32 columns</p>\n",
              "</div>\n",
              "      <button class=\"colab-df-convert\" onclick=\"convertToInteractive('df-06668314-3c60-4c9f-9f08-871b4123f88b')\"\n",
              "              title=\"Convert this dataframe to an interactive table.\"\n",
              "              style=\"display:none;\">\n",
              "        \n",
              "  <svg xmlns=\"http://www.w3.org/2000/svg\" height=\"24px\"viewBox=\"0 0 24 24\"\n",
              "       width=\"24px\">\n",
              "    <path d=\"M0 0h24v24H0V0z\" fill=\"none\"/>\n",
              "    <path d=\"M18.56 5.44l.94 2.06.94-2.06 2.06-.94-2.06-.94-.94-2.06-.94 2.06-2.06.94zm-11 1L8.5 8.5l.94-2.06 2.06-.94-2.06-.94L8.5 2.5l-.94 2.06-2.06.94zm10 10l.94 2.06.94-2.06 2.06-.94-2.06-.94-.94-2.06-.94 2.06-2.06.94z\"/><path d=\"M17.41 7.96l-1.37-1.37c-.4-.4-.92-.59-1.43-.59-.52 0-1.04.2-1.43.59L10.3 9.45l-7.72 7.72c-.78.78-.78 2.05 0 2.83L4 21.41c.39.39.9.59 1.41.59.51 0 1.02-.2 1.41-.59l7.78-7.78 2.81-2.81c.8-.78.8-2.07 0-2.86zM5.41 20L4 18.59l7.72-7.72 1.47 1.35L5.41 20z\"/>\n",
              "  </svg>\n",
              "      </button>\n",
              "      \n",
              "  <style>\n",
              "    .colab-df-container {\n",
              "      display:flex;\n",
              "      flex-wrap:wrap;\n",
              "      gap: 12px;\n",
              "    }\n",
              "\n",
              "    .colab-df-convert {\n",
              "      background-color: #E8F0FE;\n",
              "      border: none;\n",
              "      border-radius: 50%;\n",
              "      cursor: pointer;\n",
              "      display: none;\n",
              "      fill: #1967D2;\n",
              "      height: 32px;\n",
              "      padding: 0 0 0 0;\n",
              "      width: 32px;\n",
              "    }\n",
              "\n",
              "    .colab-df-convert:hover {\n",
              "      background-color: #E2EBFA;\n",
              "      box-shadow: 0px 1px 2px rgba(60, 64, 67, 0.3), 0px 1px 3px 1px rgba(60, 64, 67, 0.15);\n",
              "      fill: #174EA6;\n",
              "    }\n",
              "\n",
              "    [theme=dark] .colab-df-convert {\n",
              "      background-color: #3B4455;\n",
              "      fill: #D2E3FC;\n",
              "    }\n",
              "\n",
              "    [theme=dark] .colab-df-convert:hover {\n",
              "      background-color: #434B5C;\n",
              "      box-shadow: 0px 1px 3px 1px rgba(0, 0, 0, 0.15);\n",
              "      filter: drop-shadow(0px 1px 2px rgba(0, 0, 0, 0.3));\n",
              "      fill: #FFFFFF;\n",
              "    }\n",
              "  </style>\n",
              "\n",
              "      <script>\n",
              "        const buttonEl =\n",
              "          document.querySelector('#df-06668314-3c60-4c9f-9f08-871b4123f88b button.colab-df-convert');\n",
              "        buttonEl.style.display =\n",
              "          google.colab.kernel.accessAllowed ? 'block' : 'none';\n",
              "\n",
              "        async function convertToInteractive(key) {\n",
              "          const element = document.querySelector('#df-06668314-3c60-4c9f-9f08-871b4123f88b');\n",
              "          const dataTable =\n",
              "            await google.colab.kernel.invokeFunction('convertToInteractive',\n",
              "                                                     [key], {});\n",
              "          if (!dataTable) return;\n",
              "\n",
              "          const docLinkHtml = 'Like what you see? Visit the ' +\n",
              "            '<a target=\"_blank\" href=https://colab.research.google.com/notebooks/data_table.ipynb>data table notebook</a>'\n",
              "            + ' to learn more about interactive tables.';\n",
              "          element.innerHTML = '';\n",
              "          dataTable['output_type'] = 'display_data';\n",
              "          await google.colab.output.renderOutput(dataTable, element);\n",
              "          const docLink = document.createElement('div');\n",
              "          docLink.innerHTML = docLinkHtml;\n",
              "          element.appendChild(docLink);\n",
              "        }\n",
              "      </script>\n",
              "    </div>\n",
              "  </div>\n",
              "  "
            ]
          },
          "metadata": {},
          "execution_count": 30
        }
      ]
    },
    {
      "cell_type": "code",
      "source": [
        "import numpy as np"
      ],
      "metadata": {
        "id": "3dMjdnTgEkM7"
      },
      "execution_count": null,
      "outputs": []
    },
    {
      "cell_type": "code",
      "source": [
        "#checking for percentage of null values in each column\n",
        "for col in data.columns:\n",
        "    pct_missing = np.mean(data[col].isnull())\n",
        "    print('{} - {}%'.format(col, round(pct_missing*100)))"
      ],
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "zuc65W_FEV64",
        "outputId": "fb1870a5-4a40-41ba-ae80-d945339f8cc0"
      },
      "execution_count": null,
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "X - 0%\n",
            "Y - 0%\n",
            "OBJECTID - 0%\n",
            "CONV_ID - 0%\n",
            "NAME - 0%\n",
            "CITY - 0%\n",
            "STATE - 0%\n",
            "TELEPHONE - 0%\n",
            "TYPE - 0%\n",
            "STATUS - 0%\n",
            "COUNTY - 0%\n",
            "COUNTYFIPS - 0%\n",
            "COUNTRY - 0%\n",
            "LATITUDE - 0%\n",
            "LONGITUDE - 0%\n",
            "NAICS_CODE - 0%\n",
            "NAICS_DESC - 0%\n",
            "SOURCE - 0%\n",
            "SOURCEDATE - 0%\n",
            "VAL_DATE - 0%\n",
            "WEBSITE - 0%\n",
            "COMPLEXNM - 0%\n",
            "FORMERNM - 0%\n",
            "YEARCHNG - 0%\n",
            "FIXED_STS - 0%\n",
            "BALLROOM - 0%\n",
            "EXHIBIT - 0%\n",
            "LOBBY - 0%\n",
            "MAIN_FLOOR - 0%\n",
            "OUTDOOR - 0%\n",
            "PRE_FUNCT - 0%\n",
            "MEET_ROOMS - 0%\n"
          ]
        }
      ]
    },
    {
      "cell_type": "code",
      "source": [
        "data.to_csv('convention.csv')"
      ],
      "metadata": {
        "id": "Pu1GDiewEntr"
      },
      "execution_count": null,
      "outputs": []
    }
  ]
}